"""Semantic genre clusters for cross-content-type matching.

Groups normalized genre/tag terms into thematic clusters so that items
sharing a theme (e.g. a book tagged "space warfare" and a TV show tagged
"war") can be connected even when they share no raw terms.

Terms intentionally appear in multiple clusters (e.g. "quest" in both
*fantasy* and *adventure_exploration*) to create richer thematic links.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Cluster definitions
# ---------------------------------------------------------------------------

CLUSTERS: dict[str, set[str]] = {
    "science_fiction": {
        "science fiction",
        "cyberpunk",
        "steampunk",
        "biopunk",
        "dieselpunk",
        "solarpunk",
        "atompunk",
        "nanopunk",
        "clockpunk",
        "post-cyberpunk",
        "afrofuturism",
        "retrofuturism",
        "climate fiction",
        "hard science fiction",
        "soft science fiction",
        "military science fiction",
        "science fantasy",
        "alternate history",
        "space",
        "space opera",
        "space warfare",
        "space western",
        "robots",
        "android",
        "cyborg",
        "alien",
        "extraterrestrial",
        "time travel",
        "artificial intelligence",
        "virtual reality",
        "simulation",
        "matrix",
        "singularity",
        "transhumanism",
        "nanotechnology",
        "genetic engineering",
        "clone",
        "near future",
        "future",
        "far future",
        "parallel universe",
        "life on other planets",
        "interplanetary voyages",
        "spaceship",
        "space station",
        "space colony",
        "alien planet",
        "first contact",
        "generation ship",
        "colonization",
        "terraforming",
        "mecha",
        "galactic empire",
        "planetary romance",
        "dying earth",
        "hacking",
        "cyberspace",
        "virtual world",
        "man versus machine",
    },
    "fantasy": {
        "fantasy",
        "high fantasy",
        "epic fantasy",
        "low fantasy",
        "dark fantasy",
        "urban fantasy",
        "contemporary fantasy",
        "historical fantasy",
        "grimdark",
        "noblebright",
        "sword and sorcery",
        "portal fantasy",
        "gaslamp fantasy",
        "flintlock fantasy",
        "fairy tale retelling",
        "heroic fantasy",
        "comic fantasy",
        "cozy fantasy",
        "romantasy",
        "progression fantasy",
        "litrpg",
        "gamelit",
        "isekai",
        "wuxia",
        "xianxia",
        "magical realism",
        "new weird",
        "weird fiction",
        "magic",
        "wizard",
        "wizards",
        "witch",
        "witches",
        "sorcery",
        "dragons",
        "elves",
        "dwarves",
        "orcs",
        "fairies",
        "fae",
        "changeling",
        "shapeshifter",
        "mythology",
        "folklore",
        "fairy tale",
        "legend",
        "epic",
        "quest",
        "sword",
        "medieval",
        "knights",
        "kingdom",
        "royalty",
        "prophecy",
        "chosen one",
        "good and evil",
        "dark lord",
        "necromancy",
        "alchemy",
        "enchantment",
        "summoning",
        "elemental magic",
        "blood magic",
        "divine magic",
        "court intrigue",
        "dungeon",
        "dungeon crawler",
    },
    "war_military": {
        "war",
        "military",
        "soldier",
        "battle",
        "combat",
        "warfare",
        "guerrilla warfare",
        "tactical",
        "naval",
        "space warfare",
        "military science fiction",
        "world war",
        "world war i",
        "world war ii",
        "vietnam war",
        "cold war",
        "navy",
        "army",
        "marines",
        "special forces",
        "trench",
        "battlefield",
        "military base",
        "resistance",
        "rebellion",
        "revolution",
    },
    "horror_dark": {
        "horror",
        "supernatural",
        "supernatural horror",
        "paranormal",
        "occult",
        "gothic",
        "southern gothic",
        "vampire",
        "werewolf",
        "zombie",
        "monster",
        "creature",
        "slasher",
        "survival horror",
        "haunted house",
        "haunting",
        "ghost story",
        "possession",
        "demonic",
        "witchcraft",
        "dark",
        "cosmic horror",
        "eldritch",
        "body horror",
        "folk horror",
        "psychological horror",
        "eco horror",
        "techno horror",
        "religious horror",
        "isolation horror",
        "cult horror",
        "splatterpunk",
        "creature feature",
        "found footage",
        "dark fantasy",
        "eerie",
        "creepy",
        "unsettling",
        "disturbing",
    },
    "crime_thriller": {
        "crime",
        "thriller",
        "mystery",
        "detective",
        "spy",
        "espionage",
        "murder",
        "serial killer",
        "heist",
        "robbery",
        "kidnapping",
        "hostage",
        "police",
        "police procedural",
        "fbi",
        "cia",
        "noir",
        "neo-noir",
        "stealth",
        "conspiracy",
        "organized crime",
        "cozy mystery",
        "whodunit",
        "locked room mystery",
        "hardboiled",
        "private detective",
        "amateur sleuth",
        "psychological thriller",
        "domestic thriller",
        "legal thriller",
        "medical thriller",
        "techno thriller",
        "political thriller",
        "financial thriller",
        "caper",
        "cold case",
        "forensic",
        "true crime",
        "undercover",
    },
    "adventure_exploration": {
        "adventure",
        "exploration",
        "quest",
        "open world",
        "survival",
        "journey",
        "expedition",
        "treasure",
        "treasure hunt",
        "road trip",
        "travel",
        "pirate",
        "island",
        "frontier",
        "wilderness",
        "swashbuckler",
        "adventurer",
        "explorer",
    },
    "post_apocalyptic": {
        "apocalyptic",
        "post-apocalyptic",
        "dystopia",
        "dystopian",
        "pandemic",
        "survival",
        "disaster",
        "invasion",
        "nuclear",
        "wasteland",
        "totalitarianism",
        "plague",
    },
    "space_opera": {
        "space opera",
        "space",
        "spaceship",
        "space station",
        "space colony",
        "space warfare",
        "interplanetary voyages",
        "life on other planets",
        "alien planet",
        "galactic empire",
        "generation ship",
        "first contact",
    },
    "drama_emotional": {
        "drama",
        "emotional",
        "coming of age",
        "bildungsroman",
        "redemption",
        "friendship",
        "heartwarming",
        "heartbreaking",
        "inspiring",
        "tragic",
        "melancholic",
        "uplifting",
        "family saga",
        "social drama",
        "melodrama",
        "poignant",
        "bittersweet",
        "grief",
        "loss",
        "sacrifice",
        "forgiveness",
        "atonement",
        "hope",
        "despair",
        "identity",
        "self-discovery",
        "belonging",
        "loneliness",
        "isolation",
        "found family",
        "slice of life",
    },
    "comedy_lighthearted": {
        "comedy",
        "satirical",
        "satire",
        "parody",
        "absurd",
        "feel-good",
        "romantic comedy",
        "comic fantasy",
        "mockumentary",
        "tragicomedy",
        "whimsical",
        "lighthearted",
        "playful",
        "witty",
        "campy",
        "ironic",
        "cozy",
        "cozy fantasy",
        "cozy mystery",
        "cozy game",
    },
    "rpg_narrative": {
        "rpg",
        "action rpg",
        "jrpg",
        "crpg",
        "tactical rpg",
        "mmorpg",
        "story rich",
        "narrative",
        "choices matter",
        "multiple endings",
        "branching narrative",
        "visual novel",
        "interactive fiction",
        "litrpg",
        "gamelit",
        "immersive sim",
        "dungeon crawler",
    },
    "action_combat": {
        "action",
        "shooter",
        "first person shooter",
        "third person shooter",
        "martial arts",
        "hack and slash",
        "beat em up",
        "fight",
        "gun",
        "shootout",
        "explosion",
        "violence",
        "car chase",
        "battle royale",
        "extraction shooter",
        "bullet hell",
        "swashbuckler",
        "duel",
        "combat",
        "chase",
    },
    "strategy_tactics": {
        "strategy",
        "rts",
        "turn-based",
        "real-time",
        "grand strategy",
        "4x",
        "management",
        "puzzle",
        "tower defense",
        "city builder",
        "colony sim",
        "tycoon",
        "god game",
        "auto battler",
    },
    "historical": {
        "historical",
        "historical fantasy",
        "historical romance",
        "period piece",
        "medieval",
        "victorian",
        "edwardian",
        "elizabethan",
        "renaissance",
        "ancient",
        "classical antiquity",
        "dark ages",
        "colonial era",
        "age of sail",
        "regency",
        "belle epoque",
        "roaring twenties",
        "prohibition era",
        "great depression",
        "interwar period",
        "1920s",
        "1930s",
        "1940s",
        "1950s",
        "1960s",
        "1970s",
        "1980s",
        "1990s",
        "world war",
        "world war i",
        "world war ii",
        "cold war",
        "vietnam war",
        "alternate history",
        "biopic",
    },
    "western": {
        "western",
        "cowboy",
        "gunslinger",
        "outlaw",
        "frontier",
        "marshal",
        "spaghetti western",
        "neo-western",
        "weird western",
        "space western",
    },
    "romance": {
        "romance",
        "love",
        "marriage",
        "contemporary romance",
        "historical romance",
        "regency romance",
        "paranormal romance",
        "romantic suspense",
        "romantic comedy",
        "dark romance",
        "romantasy",
        "slow burn",
        "enemies to lovers",
        "friends to lovers",
        "forbidden love",
        "second chance",
        "love triangle",
        "star-crossed",
        "arranged marriage",
        "passionate",
    },
    # -------------------------------------------------------------------
    # New clusters for thematic areas not previously covered
    # -------------------------------------------------------------------
    "supernatural_paranormal": {
        "supernatural",
        "supernatural horror",
        "paranormal",
        "paranormal romance",
        "occult",
        "ghost story",
        "haunting",
        "haunted house",
        "possession",
        "demonic",
        "witchcraft",
        "witch",
        "witches",
        "vampire",
        "werewolf",
        "shapeshifter",
        "psychic",
        "spiritual",
    },
    "psychological": {
        "psychological",
        "psychological horror",
        "psychological thriller",
        "domestic thriller",
        "obsession",
        "madness",
        "amnesia",
        "unreliable narrator",
        "identity",
        "trauma",
        "mental health",
        "descent into madness",
        "isolation",
        "paranoia",
        "claustrophobic",
        "cerebral",
        "introspective",
    },
    "nonfiction_documentary": {
        "documentary",
        "biography",
        "memoir",
        "autobiography",
        "true crime",
        "narrative nonfiction",
        "biopic",
        "docudrama",
        "mockumentary",
        "history",
        "popular science",
        "nature writing",
        "travel writing",
        "creative nonfiction",
        "investigative journalism",
    },
}

# ---------------------------------------------------------------------------
# Pre-computed reverse index
# ---------------------------------------------------------------------------

_TERM_TO_CLUSTERS: dict[str, set[str]] = {}

for _cluster_name, _terms in CLUSTERS.items():
    for _term in _terms:
        _TERM_TO_CLUSTERS.setdefault(_term, set()).add(_cluster_name)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_clusters_for_terms(terms: list[str]) -> set[str]:
    """Return all cluster names that any of *terms* belongs to.

    Args:
        terms: Normalized genre/tag strings.

    Returns:
        Set of cluster name strings.
    """
    clusters: set[str] = set()
    for term in terms:
        matching = _TERM_TO_CLUSTERS.get(term)
        if matching:
            clusters.update(matching)
    return clusters


def cluster_overlap(terms_a: list[str], terms_b: list[str]) -> float:
    """Jaccard similarity of the cluster memberships of two term lists.

    Args:
        terms_a: First set of normalized genre/tag strings.
        terms_b: Second set of normalized genre/tag strings.

    Returns:
        Jaccard similarity in ``[0.0, 1.0]``.
    """
    clusters_a = get_clusters_for_terms(terms_a)
    clusters_b = get_clusters_for_terms(terms_b)

    if not clusters_a or not clusters_b:
        return 0.0

    intersection = clusters_a & clusters_b
    union = clusters_a | clusters_b
    return len(intersection) / len(union)
